<?php

namespace frontend\modules\user\models\relation;

use Yii;

/**
 * This is the model class for table "user_pol".
 *
 * @property int $id
 * @property int|null $user_id
 * @property int|null $prop_id
 */
class UserPol extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user_pol';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'prop_id'], 'integer'],
        ];
    }

    public function beforeSave($insert)
    {

        UserPol::deleteAll(['user_id' => $this->user_id]);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'Post ID',
            'prop_id' => 'Pol ID',
        ];
    }
}
