<?php

namespace frontend\modules\user\models\relation;

use Yii;

/**
 * This is the model class for table "user_worck_time".
 *
 * @property int $id
 * @property int|null $post_id
 * @property int|null $from
 * @property int|null $to
 */
class UserWorckTime extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user_worck_time';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['post_id', 'from', 'to'], 'integer'],
        ];
    }

    public function beforeSave($insert)
    {

        UserWorckTime::deleteAll(['post_id' => $this->post_id]);

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'post_id' => 'Post ID',
            'from' => 'From',
            'to' => 'To',
        ];
    }
}
